# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
[es]
  languageCode = "es-mx"
  contentDir = "content/es"
  [es.params]
    description = "Boigrafía de Ramón Reyes Carrión"
  [[es.menu.main]]
    name = "Inicio"
    url = "#about"
    weight = 10
  [[es.menu.main]]
    name = "Academia"
    url = "#posts"
    identifier = "acad"
    weight = 20
  [[es.menu.main]]
    name = "Proyectos"
    url = "#projects"
    weight = 30
  [[es.menu.main]]
    name = "Charlas"
    url = "#talks"
    weight = 23
    parent = "acad"
  [[es.menu.main]]
    name = "Tesis"
    url = "#tesis"
    weight = 22
    parent = "acad"
  [[es.menu.main]]
    name = "Publicaciones"
    url = "#featured"
    weight = 50
  [[es.menu.main]]
    name = "Cursos"
    url = "#posts"
    weight = 21
    parent = "acad"
  [[es.menu.main]]
    name = "Contacto"
    url = "#contact"
    weight = 70
# Uncomment the lines below to configure your website in a second language.
#[zh]
#  languageCode = "zh-Hans"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
