# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10
[[main]]
  name = "Experience"
  url = "#experience"
  weight = 15
[[main]]
  name = "Academia"
  url = "#posts"
  weight = 20
  identifier = "acad"
[[main]]
  name = "Technology"
  url = "#projects"
  weight = 30
  identifier = "tec"
[[main]]
  name = "Skills"
  url = "#skils"
  weight = 32
  parent = "tec"
[[main]]
  name = "Courses"
  url = "#posts"
  weight = 22
  parent = "acad"
[[main]]
  name = "Projects"
  url = "#projects"
  weight = 31
  parent = "tec"
[[main]]
  name = "Talks"
  url = "#talks"
  weight = 60
[[main]]
  name = "Thesis"
  url = "#tesis"
  weight = 23
  parent = "acad"
[[main]]
  name = "Publications"
  url = "#featured"
  weight = 21
  parent = "acad"
[[main]]
  name = "#accomplishments"
  url = "#accomplishments"
  weight = 24
  parent = "tec"
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
